// Generated by CoffeeScript 1.12.2
(function() {
  var all_code, step;

  all_code = "";

  step = 1;

  $(function() {
    var counter, update;
    hljs.initHighlightingOnLoad();
    counter = 0;
    $.ajax({
      url: 'js/sample.js',
      success: function(res) {
        return all_code = res;
      }
    });
    update = function() {
      var code;
      counter += step;
      if (counter > all_code.length) {
        counter = all_code.length;
      }
      code = all_code.slice(0, counter);
      $('code').text(code);
      return $('pre code').each(function(i, block) {
        return hljs.highlightBlock(block);
      });
    };
    $('body').keydown(function() {
      return update();
    });
    return $('.button').click(function() {
      $('code').text(all_code);
      return $('pre code').each(function(i, block) {
        return hljs.highlightBlock(block);
      });
    });
  });

}).call(this);
